@startmindmap
* DateTimeUtils

** 时间构建模式（TimeMode）
***_ NOW_OF_DAY（当前日期时间）
***_ BEGIN_OF_DAY（开始日期时间）
***_ END_OF_DAY（结束日期时间）

** 创建实例
*** 从当前日期时间创建
****_ newDataTime
****_ newBeginDate
****_ newEndDate
****_ now
****_ nowDateTime
*** 从其他日期时间创建
****_ newDateTime
****_ newBeginDate
****_ newEndDate
****_ beginOfDate
****_ endOfDate
****_ beginOfMonth（月的第一天）
****_ endOfMonth（月的最后一天）
*** 从时间戳创建
****_ newDateTime
****_ newBeginDate
****_ newEndDate
*** 从部分年月日时分秒毫秒创建
****_ newDateTime
****_ newBeginDate
****_ newEndDate
****_ nowDateTimeOfNowDate
****_ newDateTimeOfNowTime
*** 从可变的年月日时分秒毫秒数组创建
****_ newDateTimeOfArray（元素必须依次为年月日时分秒毫秒）
*** 从时区创建当前时间
****_ nowDateTime
****_ now
*** 昨天今天明天
****_ yesterday
****_ beginOfYesterday
****_ endOfYesterday
****_ today
****_ beginOfToday
****_ endOfToday
****_ tomorrow
****_ beginOfTomorrow
****_ endOfTomorrow
*** 日期范围列表
****_ getDateList

** 日期时间分析
*** 日期时间值
**** 值列表
*****_ toArray
**** 年份值
*****_ nowYear
*****_ getYear
**** 月份值
*****_ nowMonth
*****_ getMonth
**** 日期值
*****_ nowDay
*****_ getDay
**** 星期值
*****_ nowWeek
*****_ getWeek
**** 小时值
*****_ nowHour
*****_ getHour
**** 分钟值
*****_ nowMinute
*****_ getMinute
**** 秒值
*****_ nowSecond
*****_ getSecond
**** 毫秒值
*****_ nowMillisecond
*****_ getMillisecond
*** 是否是闰年
****_ isLeapYear
****_ nowYearIsLeap
*** 一年中的第几天
****_ nowDayOfYear
****_ getDayOfYear
*** 一月中的第几天
****_ nowDay
****_ getDayOfYear
*** 一年周的第几周
****_ nowWeekOfYear
****_ getWeekOfYear
*** 一月中的第几周
****_ nowWeekOfMonth
****_ getWeekOfMonth
*** 一年的天数
****_ nowYearDays
****_ getDaysOfYear
*** 一月的天数
****_ nowMonthDays
****_ getDaysOfMonth
*** 时间戳
****_ nowTimestamp
****_ timestamp


** 日期时间运算
*** 加减运算
**** 年
*****_ addYears
*****_ minusYears
**** 月
*****_ addMonths
*****_ minusMonths
**** 天
*****_ addDays
*****_ minusDays
**** 小时
*****_ addHours
*****_ minusHours
**** 分钟
*****_ addMinutes
*****_ minusMinutes
**** 秒
*****_ addSeconds
*****_ minusSeconds
**** 混合运算
***** 月日混合
******_ addMD
******_ minusMD
***** 时分混合
******_ addHM
******_ minusHM
**** 差值计算
*****_ diffArray（年月日时分秒毫秒）
**** 相差天数
*****_ diffDays（不足1天不计入）
*****_ intervalDays（相隔的天数）
*****_ spanDays（跨越的天数）
*** 比较运算
**** 大小比较（返回1，0，-1）
*****_ compare
*****_ compareWithNow（和当天比较）
**** 前后比较（返回true，false）
*****_ before
*****_ beforeOfNow
*****_ after
*****_ afterOfNow
**** 相等比较（返回true，false）
*****_ equals
*****_ equalsOfNow
*****_ beforeOrEquals
*****_ afterOrEquals
*****_ beforeOrEqualsOfNow
*****_ afterOrEqualsOfNow
**** 是否同一天
*****_ sameDay
**** 昨天今天明天
*****_ isYesterday
*****_ isToday
*****_ isTomorrow
*****_ beforeOfTomorrow（今天或今天之前）
*****_ afterOfYesterday（今天或今天之后）


** 日期时间格式化
*** 默认配置
****_ yyyy/MM/dd HH:mm:ss（日期时间格式）
****_ yyyy/MM/dd（日期格式化）
****_ HH:mm:ss（时间格式）
*** 格式化为字符串
**** 默认转换
*****_ format
*****_ formatOfNow
*****_ formatDate
*****_ formatDateOfNow
*****_ formatTime
*****_ formatTimeOfNow
**** 指定格式转换
*****_ format
*****_ formatOfNow
*****_ formatDate
*****_ formatDateOfNow
*****_ formatTime
*****_ formatTimeOfNow
**** 指定语言环境转换
*****_ format
*****_ formatOfNow
**** 原日期实际字符串转换为另一个格式字符串
*****_ format
*** 转换为日期时间


** 日期时间转换
*** 字符串转换
****_ parse
****_ tryToParse（尝试多个字符串格式进行转换）
*** 时间戳转换
****_ parse
*** SQLDate转换
****_ parse
*** SQLTimestamp转换
****_ parse

** 其他日期时间
*** 创建SQLDate
****_ nowSQLDateTime
*** 转换为SQLDate
****_ parseSQLDate
*** 创建SQLTimestamp
****_ newSQLTimestamp
*** 转换为SQLTimestamp
****_ parseSQLTimestamp




@endmindmap