@startmindmap
* SystemInfo

** HARDWARE
*** CPU_ENDIAN
****_ 属性名：sun.cpu.endian
****_ 默认值：无
*** CPU_ISALIST
****_ 属性名：sun.cpu.isalist
****_ 默认值：无

** OS
*** LINE_SEPARATOR
****_ 属性名：line.separator
****_ 默认值：\\r\\n
*** FILE_SEPARATOR
****_ 属性名：file.separator
****_ 默认值：\\
*** PATH_SEPARATOR
****_ 属性名：path.separator
****_ 默认值：;
*** ARCH
****_ 属性名：os.arch
****_ 默认值：无
*** NAME
****_ 属性名：os.name
****_ 默认值：无
*** VERSION
****_ 属性名：os.version
****_ 默认值：无
*** ENCODING
****_ 属性名：sun.jnu.encoding
****_ 默认值：无
*** GUI
****_ 属性名：sun.desktop
****_ 默认值：无

** USER
*** COUNTRY
****_ 属性名：user.country
****_ 默认值：CN
*** TIMEZONE
****_ 属性名：user.timezone
****_ 默认值：GMT+8:00
*** LANGUAGE
****_ 属性名：user.language
****_ 默认值：zh
*** TEMP_DIR
****_ 属性名：java.io.tmpdir
****_ 默认值：无
*** HOME_DIR
****_ 属性名：user.home
****_ 默认值：无
*** NAME
****_ 属性名：user.name
****_ 默认值：无

** JAVA
*** CLASS_VERSION
****_ 属性名：java.class.version
****_ 默认值：无
*** SPECIFICATION_VERSION
****_ 属性名：java.specification.version
****_ 默认值：无
*** VM_SPECIFICATION_VERSION
****_ 属性名：java.vm.specification.version
****_ 默认值：无
*** VERSION
****_ 属性名：java.version
****_ 默认值：无
*** RUNTIME_VERSION
****_ 属性名：java.runtime.version
****_ 默认值：无
*** COMPILER
****_ 属性名：sun.management.compiler
****_ 默认值：无
*** HOME
****_ 属性名：java.home
****_ 默认值：无
*** RUNTIME_ROOT_PATH
****_ 属性名：sun.boot.library.path
****_ 默认值：无
*** RUNTIME_ROOT_CLASS_PATH
****_ 属性名：sun.boot.class.path
****_ 默认值：无
*** LIBRARY_PATH
****_ 属性名：java.library.path
****_ 默认值：无
*** CLASS_PATH
****_ 属性名：java.class.path
****_ 默认值：无
*** EXTEND_CLASS_PATH
****_ 属性名：java.ext.dirs
****_ 默认值：无
*** GUI_GRAPHICS_CLASS
****_ 属性名：java.awt.graphicsenv
****_ 默认值：无
*** GUI_PRINTER_CLASS
****_ 属性名：java.awt.printerjob
****_ 默认值：无
*** GUI_TOOLKIT_CLASS
****_ 属性名：awt.toolkit
****_ 默认值：无
*** ARCH_DATA_BITS
****_ 属性名：sun.arch.data.model
****_ 默认值：无
*** FILE_ENCODING
****_ 属性名：file.encoding
****_ 默认值：UTF-8
*** IO_UNICODE_ENCODING
****_ 属性名：sun.io.unicode.encoding
****_ 默认值：无
*** CURRENT_RUN_INFO
****_ 属性名：sun.java.command
****_ 默认值：无

@endmindmap