@startmindmap
* SystemUtils

** 国家简称
***_ getCountryShortName
** 时区
***_ getTimezone
** 语言
***_ getLanguage
** Java版本
***_ getJavaVersion
** 文件编码
***_ getFileEncoding
** 换行符
***_ getLineSeparator
** 文件分隔符
***_ getFileSeparator
** 路径分隔符
***_ getPathSeparator

@endmindmap

