@startuml

interface StringFormatter {
    +format() : String
}
abstract class AbstractStringFormatter
class Slf4jStringFormatter

StringFormatter <|.. AbstractStringFormatter
AbstractStringFormatter <|-- Slf4jStringFormatter

interface Comparator<T>
class StringDictComparator<String>

Comparator <|.. StringDictComparator

interface RandomStringFactory {
    +random() : String
}
abstract class AbstractRandomStrFactory
class RandomAlphabetStrFactory
class RandomDigitStrFactory
class RandomAlphanumericStrFactory

RandomStringFactory <|.. AbstractRandomStrFactory
AbstractRandomStrFactory <|-- RandomAlphabetStrFactory
AbstractRandomStrFactory <|-- RandomDigitStrFactory
AbstractRandomStrFactory <|-- RandomAlphanumericStrFactory

@enduml