@startmindmap
<style>
mindmapDiagram {
    node {
        BackgroundColor #Business
    }
}
</style>
* 核心库
** 工具库

*** 数组
**** Util
*****_ ArrayUtils

*** 集合
**** Util
*****_ CollectionUtils
*****_ MapUtils
**** 分页
*****_ Pageable
*****_ ListPage
*****_ Page

*** 枚举
**** Util
*****_ EnumUtils
**** 字典
*****_ DictionaryEnumeration

*** 对象
**** Util
*****_ ObjectUtils <font color=red><&info><sup>待完善</sup></font>

*** 字符串
**** Util
*****_ StringUtils
**** 格式化
*****_ StringFormatter
*****_ Slf4jStringFormatter
***** 格式串构建器
******_ PatternString
******_ PatternMessage
******_ PatternStringBuilder
******_ PatternMessageBuilder
**** 排序
*****_ StringDictComparator
**** 随机字符串
*****_ RandomStringFactory

*** 反射
**** Util
*****_ ClassUtils <font color=red><&info><sup>待完善</sup></font>

*** 文件
**** Util
*****_ FileUtils <font color=red><&info><sup>待完善</sup></font>
*****_ PropertiesFileUtils <font color=red><&info><sup>待完善</sup></font>


*** 日期时间
**** Util
*****_ DateTimeUtils

*** 表达式
**** 路径匹配
*****_ PathMatcher
***** Ant
******_ AntPathMatcher
**** 正则匹配
***** Util
******_ RegexUtils <font color=red><&info><sup>待完善</sup></font>

** 组件库
*** 通用组件
**** 转换器
*****_ Converter
*****_ ConverterException

**** 匹配器
*****_ Matcher

*** 字符集
**** <del>Unicode</del>

@endmindmap