@startmindmap
<style>
mindmapDiagram {
    node {
        BackgroundColor #Business
    }
}
</style>

* ClassUtils

** 类型分析
*** 类型判断
****_ isPrimitiveType
****_ isWrapperType
****_ isValueType
*****_ <b>registerValueType</b> <font color=red><&info><sup>辅助函数</sup></font>
****_ isArrayType
*** 关系分析
****_ implementOf
****_ extendsOf

** 类定义分析
*** 类加载器和路径
****_ getDefaultClassLoader
****_ getDefaultClassLoadURL
****_ getClassLoader
****_ getClassLoadURL
****_ getCurrentClassURL
*** 类名称
****_ getFullName
****_ getAbbreviatedName
****_ getShortName
*** 在某个包下
****_ fromPackage
****_ matchPackage
*** 泛型
****_ isDeclaredGenericType
****_ isGenericType
****_ getDeclaredGenericType
****_ getActualGenericType
*** 注解
****_ hasAnnotation
****_ getAnnotations


** 类内容分析
*** 字段/属性
****_ getContainFields
****_ getDeclaredFields
****_ getDeclaredField
****_ containField
****_ declaredField


*** 构造函数
****_ getDeclaredConstructors
****_ getDeclaredConstructor
****_ declaredConstructor

*** 方法
****_ getContainMethods
****_ getDeclaredMethods
****_ containMethod
****_ declaredMethod

@endmindmap