@startmindmap
<style>
mindmapDiagram {
    node {
        BackgroundColor #Business
    }
}
</style>

* DateTimeUtils

** 时间构建模式（TimeMode）
***_ NOW_OF_DAY（当前日期时间）
***_ BEGIN_OF_DAY（开始日期时间）
***_ END_OF_DAY（结束日期时间）

** 实例化
*** 创建日期时间
**** 基于指定日期时间
*****_ newDateTime
*****_ newDateTimeOfArray
*****_ newDateTimeOfNowTime
*****_ newDateTimeOfNowDate
**** 基于当前日期时间
*****_ now
*****_ <del>nowDateTime</del>

*** 创建开始/结束日期时间
**** 基于指定日期时间
*****_ newBeginDate
*****_ newEndDate
*****_ beginOfDate
*****_ endOfDate
*****_ beginOfMonth
*****_ endOfMonth
*****_ beginOfYear
*****_ endOfYear
**** 基于当前日期时间
*****_ <del>nowBeginDate</del>
*****_ <del>nowEndDate</del>
*****_ beginOfNow
*****_ endOfNow
*****_ beginOfNowMonth
*****_ endOfNowMonth
*****_ beginOfNowYear
*****_ endOfNowYear

** 日期时间分析
*** 基于指定日期时间
****_ isLeapYear
****_ toArray
****_ getYear
****_ getMonth
****_ getDay
****_ getHour
****_ getMinute
****_ getSecond
****_ getMillisecond
****_ getWeekOfYear
****_ getWeekOfMonth
****_ getDayOfYear
****_ getDayOfMonth
*** 基于当前日期时间
****_ nowIsLeapYear
****_ nowToArray
****_ getNowYear
****_ getNowMonth
****_ getNowDay
****_ getNowHour
****_ getNowMinute
****_ getNowSecond
****_ getNowMillisecond
****_ getWeekOfNowYear
****_ getWeekOfNowMonth
****_ getDayOfNowYear
****_ getDayOfNowMonth
*** 总天数
**** 基于指定日期时间
*****_ getMonthDays
*****_ getYearDays
**** 基于当前日期时间
*****_ getNowMonthDays
*****_ getNowYearDays

** 日期时间格式化字符串
*** 默认配置
****_ yyyy/MM/dd HH:mm:ss（日期时间格式）
****_ yyyy/MM/dd（日期格式化）
****_ HH:mm:ss（时间格式）
*** 格式化为字符串
**** 基于指定日期时间
*****_ format
*****_ formatDate
*****_ formatTime
**** 基于当前日期时间
*****_ formatOfNow
*****_ formatDateOfNow
*****_ formatTimeOfNow
**** 原日期实际字符串转换为另一个格式字符串
*****_ format

** 类型转换
*** 字符串转换为日期
****_ parse
****_ tryToParse（尝试多个字符串格式进行转换）
*** 时间戳/SQLDate/SQLTimestamp转换为日期
****_ parse
*** LocalDate/LocalDateTime/LocalTime转换
****_ parse

** 日期运算
*** 加减运算
**** 基于指定日期时间
*****_ addYears
*****_ minusYears
*****_ addMonths
*****_ minusMonths
*****_ addDays
*****_ minusDays
*****_ addHours
*****_ minusHours
*****_ addMinutes
*****_ minusMinutes
*****_ addSeconds
*****_ minusSeconds
**** 基于当前日期时间
*****_ addMonthsOfNow
*****_ minusMonthsOfNow
*****_ addDaysOfNow
*****_ minusDaysOfNow
*****_ addHoursOfNow
*****_ minusHoursOfNow
*****_ addMinutesOfNow
*****_ minusMinutesOfNow
**** 混合运算
*****_ addMD
*****_ minusMD
*****_ addHM
*****_ minusHM
*** 差值运算
****_ diffArray（年月日时分秒毫秒）
**** 相差天数
*****_ diffDays（不足1天不计入）
*****_ intervalDays（相隔的天数）
*****_ spanDays（跨越的天数）
*** 比较运算
****_ sameDay
**** 大小比较（返回1，0，-1）
*****_ compare
*****_ compareWithNow（和当天比较）
**** 前后比较（返回true，false）
*****_ before
*****_ beforeOfNow
*****_ after
*****_ afterOfNow
**** 相等比较（返回true，false）
*****_ equals
*****_ equalsOfNow
*****_ beforeOrEquals
*****_ afterOrEquals

** 昨天今天明天
*** 实例化
****_ yesterday
****_ beginOfYesterday
****_ endOfYesterday
****_ today
****_ beginOfToday
****_ endOfToday
****_ tomorrow
****_ beginOfTomorrow
****_ endOfTomorrow
*** 比较
****_ isYesterday
****_ isToday
****_ isTomorrow
****_ beforeOfTomorrow（今天或今天之前）
****_ afterOfYesterday（今天或今天之后）

** 转换为其他日期时间
***_ toSQLDate
***_ toSQLTimestamp
***_ toLocalDateTime
***_ toLocalDate
***_ toLocalTime

@endmindmap